@startuml
autonumber "<b>[00]"

title Inserimento utente

actor "Bibliotecario" as user
participant UserView
participant UserController
participant UserService
entity User
participant "UserRepository\n<<interface>>" as UserRepository #pink
participant FileBackedUserRepository
participant InMemoryUserRepository
participant FileManager
database filesystem

user -> UserView: seleziona la funzionalità di gestione utenti
UserView --> user: mostra UI di gestione utenti


user -> UserView: Inserisci dati utente e clicca "Salva"
UserView -> UserController: addUserAction()

UserController -> UserService: addUser(userData)

note over UserService
Validazione dei dati utente
es. formato email, campi obbligatori
formato matricola, ecc.
end note

UserService -> UserService: valida dati

alt UserService: validazione fallita?
    UserService --> UserController: errore di validazione\nthrow validation exception
    UserController --> UserView: showErrorMessage(exception)
    UserView --> user: mostra messaggio di errore
else validazione ok
    UserService -> User: user = new User(userData)
    UserService -> UserRepository: save(user)
    UserRepository -> FileBackedUserRepository: save(user)
    FileBackedUserRepository -> InMemoryUserRepository: save(user)
    FileBackedUserRepository -> FileManager: persistAllUsers()
    FileManager -> filesystem: write user\ndata to file

    FileManager --> FileBackedUserRepository: ack
    FileBackedUserRepository --> UserRepository: ack

    UserRepository --> UserService: ack
    UserService --> UserController: utente creato con successo
    UserController --> UserView: update user list
    UserController --> UserView: clear form data
    UserView --> user: mostra UI aggiornata
end


@enduml